version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: wqm-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Bhuvan123
      MYSQL_DATABASE: wqm
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: .
    container_name: wqm-backend
    depends_on:
      - mysql
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/wqm
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Bhuvan123

volumes:
  mysql-data:
